### PR TITLE
VS2017 support

### PR DESCRIPTION
**Pull request by bitlinker**
Hi! Please review and merge changes for modern C++ compiler (VS2017) - "array" replaced with "NifArray", because "array" is a reserved keyword now.

Please take a look at submodules also - I created pull request for the docsys repo as well.

### CODE REVIEW

**Comment by ExE-Boss** [comment]
Please, squash your commits if possible and try to follow the git commit naming convention<sup>[1](#user-content-issuecomment-345779780-ft-1 "How to Write a Git Commit Message
Git - Contributing to a Project")</sup>.

<table><tbody><tr><th valign="top">
<sup id="issuecomment-345779780-ft-1">1</sup>
</th><td valign="top">
<a href="https://chris.beams.io/posts/git-commit/">How to Write a Git Commit Message</a><br/>
<a href="https://chris.beams.io/posts/git-commit/">Git - Contributing to a Project</a> (official, but hard to read, summarized in the above link)
</tbody></td></tr></table>

**Comment by neomonkeus** [comment]
@ExE-Boss Did you mean to comment on this ticket?

**Comment by hexabits** [comment]
Yes it's really just overall very odd to push multiple conventions on a pull request with no prior contributions or even contact.   Not to mention you squash when you merge the PR, not before... 

As for the PR, we have somebody currently overhauling niflib and nifdocsys and they didn't agree with this approach.   As far as I can tell,  `array` is only in Visual C++/**CLI** and has been for many years.  You are likely including the entire `cli` namespace in whatever is using niflib.   So this is a namespace issue.

`array` is not a reserved keyword in any C/C++ standard.   AFAICT, `array` in niflib can be replaced with `std::array` anyway.

**Comment by ExE-Boss** [comment]
Yes, I meant to comment on this ticket because I have been following NifTools development for a while now and wanted to make sure that the commit info was good according to the official git commit naming convention, but I wasn’t aware of the behind the scenes niflib and nifdocsys overhaul, because it isn’t mentioned anywhere (the last commit to this repo was 5 years ago).

**Comment by neomonkeus** [comment]
@ExE-Boss Yeah... From our perspective, it just came across as some randomer commenting on what the project conventions should be, for a project they never contributed to. 

General preference is keep multiple commits, amend commit messages as required. More intent is gotten from multiple commits for a feature, which gets lost when you squash. Pinch of salt, massive generalizing, multiple factors, size of PR etc.

As per @jonwd7's comment, though that point is moot, we should really have addressed this PR sooner as there is work on-going to update niflib (we are waiting for a public push by the contributor in question).

@bitlinker, @ExE-Boss 
Suggest dropping by the [forum](forum.niftools.org) and [discord ](https://discordapp.com/invite/ZFjdN4x) to get up to speed if you interested in the development side of things, we can always do with more bodies to contribute

**Comment by bitlinker** [comment]
@ExE-Boss, @neomonkeus, @jonwd7, thanks for review. I don't have much opensource contributing experience, so I'll be more careful with tidy PRs now.

As for the **array** word, my bad, this is not a keyword. It seems to be conflicting with **std::array** implementation, because several library headers are including entire std namespace:
niflib.h:56 for example:
```
using namespace std;
```
It's not like I'm using Visual C++/CLI or including it from the client code.

VS2017 compiler output for niflib, commit 8c81e2073ce05e93dd65a30994b87f2c090cc7bc:
```
1>------ Build started: Project: niflib, Configuration: Debug - Static Win32 ------
1>bhkRigidBody.cpp
1>src\obj\bhkRigidBody.cpp(572): error C2872: 'array': ambiguous symbol
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(902): note: could be 'std::array'
1>d:\!github\niflib\include\gen\../nif_basic_types.h(81): note: or       'Niflib::array'
1>src\obj\bhkRigidBody.cpp(572): error C2974: 'std::array': invalid template argument for '_Ty', type expected
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(902): note: see declaration of 'std::array'
1>src\obj\bhkRigidBody.cpp(572): error C2993: 'unsigned short': illegal type for non-type template parameter '_Size'
1>src\obj\bhkRigidBody.cpp(572): error C2556: 'std::array Niflib::bhkRigidBody::GetUnknown7Shorts(void) const': overloaded function differs only by return type from 'Niflib::array<7,unsigned short> Niflib::bhkRigidBody::GetUnknown7Shorts(void) const'
1>d:\!github\niflib\src\obj\../../include/obj/bhkRigidBody.h(329): note: see declaration of 'Niflib::bhkRigidBody::GetUnknown7Shorts'
1>src\obj\bhkRigidBody.cpp(572): error C2371: 'Niflib::bhkRigidBody::GetUnknown7Shorts': redefinition; different basic types
1>d:\!github\niflib\src\obj\../../include/obj/bhkRigidBody.h(329): note: see declaration of 'Niflib::bhkRigidBody::GetUnknown7Shorts'
1>src\obj\bhkRigidBody.cpp(576): error C2872: 'array': ambiguous symbol
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(902): note: could be 'std::array'
1>d:\!github\niflib\include\gen\../nif_basic_types.h(81): note: or       'Niflib::array'
1>src\obj\bhkRigidBody.cpp(576): error C2974: 'std::array': invalid template argument for '_Ty', type expected
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(902): note: see declaration of 'std::array'
1>src\obj\bhkRigidBody.cpp(576): error C2993: 'unsigned short': illegal type for non-type template parameter '_Size'
1>src\obj\bhkRigidBody.cpp(576): error C2511: 'void Niflib::bhkRigidBody::SetUnknown7Shorts(const std::array &)': overloaded member function not found in 'Niflib::bhkRigidBody'
1>d:\!github\niflib\src\obj\../../include/obj/bhkRigidBody.h(37): note: see declaration of 'Niflib::bhkRigidBody'
1>src\obj\bhkRigidBody.cpp(577): error C2597: illegal reference to non-static member 'Niflib::bhkRigidBody::unknown7Shorts'
1>bhkBoxShape.cpp
1>src\obj\bhkBoxShape.cpp(128): error C3861: 'min': identifier not found
1>NiGeometryData.cpp
1>src\obj\NiGeometryData.cpp(510): error C3861: 'max': identifier not found
1>NiGeometry.cpp
1>src\obj\NiGeometry.cpp(652): error C2872: 'array': ambiguous symbol
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(902): note: could be 'std::array'
1>d:\!github\niflib\include\nif_basic_types.h(81): note: or       'Niflib::array'
1>src\obj\NiGeometry.cpp(652): error C2974: 'std::array': invalid template argument for '_Ty', type expected
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\tuple(902): note: see declaration of 'std::array'
1>src\obj\NiGeometry.cpp(652): error C2993: 'Niflib::Ref<Niflib::NiProperty>': illegal type for non-type template parameter '_Size'
1>src\obj\NiGeometry.cpp(652): error C2556: 'std::array Niflib::NiGeometry::GetBSProperties(void)': overloaded function differs only by return type from 'Niflib::array<2,Niflib::Ref<Niflib::NiProperty>> Niflib::NiGeometry::GetBSProperties(void)'
1>d:\!github\niflib\src\obj\../../include/obj/NiGeometry.h(189): note: see declaration of 'Niflib::NiGeometry::GetBSProperties'
1>src\obj\NiGeometry.cpp(652): error C2371: 'Niflib::NiGeometry::GetBSProperties': redefinition; different basic types
1>d:\!github\niflib\src\obj\../../include/obj/NiGeometry.h(189): note: see declaration of 'Niflib::NiGeometry::GetBSProperties'
1>Generating Code...
1>Done building project "niflib.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Anyway, it's good to hear that the work is on-going, the repo looks dead for several years =) Looking forward for the next releases.

**Comment by neomonkeus** [comment]
Yeah we can definitely think about the code generation side of the house if that is an improvement that we should do.

**Pull request closed without merging**
